"""Add image_url

Revision ID: 461887dff3d8
Revises: 0001
Create Date: 2026-07-13 13:34:29.293364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '461887dff3d8'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('impact_stats', 'value',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'image_url')
    op.drop_column('products', 'image_url')
    op.alter_column('impact_stats', 'value',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
